// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {azopenai} from '../models';

export function DestroyCurrentAssistant():Promise<void>;

export function GetAssistantConfig():Promise<azopenai.AssistantConfig>;

export function InitAssistant(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<number>):Promise<void>;

export function IsValidAssistantConfig():Promise<boolean>;

export function SendChatForAssistant(arg1:string):Promise<Array<string>>;

export function UploadFileAndAssociateAssistant(arg1:string):Promise<void>;
