// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DestroyCurrentAssistant() {
  return window['go']['main']['App']['DestroyCurrentAssistant']();
}

export function GetAssistantConfig() {
  return window['go']['main']['App']['GetAssistantConfig']();
}

export function InitAssistant(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InitAssistant'](arg1, arg2, arg3, arg4, arg5);
}

export function IsValidAssistantConfig() {
  return window['go']['main']['App']['IsValidAssistantConfig']();
}

export function SendChatForAssistant(arg1) {
  return window['go']['main']['App']['SendChatForAssistant'](arg1);
}

export function UploadFileAndAssociateAssistant(arg1) {
  return window['go']['main']['App']['UploadFileAndAssociateAssistant'](arg1);
}
